name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 8 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (Optional) Run workflow on pushes to master/main branches,
  # but only when main.yml is changed
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/main.yml
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Artifacts
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: artifacts.svg
          # config_display: large
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          # base_indepth: yes
          config_order: base.header, isocalendar, languages, repositories, stargazers, pagespeed, topics
          
          plugin_isocalendar: yes
          # plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_ignored: Procfile, Ruby, PureBasic, Liquid, less, qmake, lex, gnuplot, vue, scala, ejs, Jupyter Notebook, HTML, SCSS, CSS, TeX, Dockerfile, Makefile, Shell
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 7
          # plugin_languages_indepth_custom: Richard5678/cs241, Richard5678/Transformers
          # plugin_languages_analysis_timeout: 60
          # plugin_languages_analysis_timeout_repositories: 15
          
          plugin_topics: yes
          plugin_topics_limit: 10
          # plugin_topics_mode: icons

          plugin_repositories: yes
          plugin_repositories_featured: Richard5678/Alignment_Algorithms, Richard5678/Transformers
          
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://richard5678.github.io/

          plugin_stargazers: yes


      - name: Progress
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: progress.svg

          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_order: habits, wakatime, leetcode, leetcode, achievements

          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: America/Los_Angeles

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills
          plugin_leetcode_user: Richard6469

          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

